[package]
name = "design-2"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "=0.30.0-alpha.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"